[versions]
kotlin = "2.3.10"
ktlint = "14.0.1"
detekt = "2.0.0-alpha.2"
spring = "4.0.3"
arrow-kt = "2.2.1.1"
mockk = "1.14.9"
slf4j = "2.0.17"
kotest = "6.1.3"
kotest-extensions-arrow = "2.0.0"
kover = "0.9.7"
coroutines = "1.10.1"
jooq = "3.20.11"
dgs = "11.1.0"
dgs-codegen = "8.3.0"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow-kt" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor" }
jooq-meta-extensions = { group = "org.jooq", name = "jooq-meta-extensions", version.ref = "jooq" }
dgs-platform = { group = "com.netflix.graphql.dgs", name = "graphql-dgs-platform-dependencies", version.ref = "dgs" }
dgs-spring-graphql-starter = { group = "com.netflix.graphql.dgs", name = "graphql-dgs-spring-graphql-starter", version.ref = "dgs" }
graphql-extended-scalars = { group = "com.graphql-java", name = "graphql-java-extended-scalars" }
detekt-api = { group = "dev.detekt", name = "detekt-api", version.ref = "detekt" }
detekt-cli = { group = "dev.detekt", name = "detekt-cli", version.ref = "detekt" }
# Test libraries
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-arrow = { group = "io.kotest.extensions", name = "kotest-assertions-arrow", version.ref = "kotest-extensions-arrow" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring = { id = "org.springframework.boot", version.ref = "spring" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
dgs-codegen = { id = "com.netflix.dgs.codegen", version.ref = "dgs-codegen" }
