[versions]
kotlin = "2.3.10"
ktlint = "14.0.1"
spring = "4.0.3"
spring-dependencies = "1.1.7"
arrow-kt = "2.2.1.1"
mockk = "1.14.9"
slf4j = "2.0.17"
kotest = "6.1.3"
kotest-extensions-arrow = "2.0.0"
kover = "0.9.7"

[libraries]
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow-kt" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor" }
# Test libraries
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-arrow = { group = "io.kotest.extensions", name = "kotest-assertions-arrow", version.ref = "kotest-extensions-arrow" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring = { id = "org.springframework.boot", version.ref = "spring" }
spring-dependencies = { id = "io.spring.dependency-management", version.ref = "spring-dependencies" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
